### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by luohui8891**
Fix the issue about the view auto stop by iOS system when present a ~~model~~ modal view.

### CODE REVIEW

**Comment by yujinakayama** [comment]
> when present a model view.

Did you mean _modal_ view?

**Comment by luohui8891** [comment]
@yujinakayama Yes, it's typo.

**Comment by Stunner** [comment]
This change is much needed and is an elegant solution to fixing the problem where the playback indicator pauses when pushing another view onto the navigation stack occurs. This definitely fixes the issue I am seeing. It appears that the TravisCi build failed before it even got to run checks so please don't let that deter you from merging in this change. If you could rerun the CI tests that would be great. Thanks.

**Comment by luohui8891** [comment]
@Stunner looks like configuration issue of the CI. 
And I don't know whether @yujinakayama keep update this repo.
Anyway, you can specify the pod to my forked repo.

**Pull request closed without merging**
